version: '3.1'

services:
  app:
    container_name: TransactionsRoutineApp
    build: 
      context: .
      dockerfile: Dockerfile
    command: fresh
    volumes:
      - "./:/app"
    ports:
      - "8080:8080"
    depends_on: 
      - "db"
    env_file: 
      - .env

  db:
    container_name: TransactionsRoutineDatabase
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: transaction_routine
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - ./init/schema.sql:/docker-entrypoint-initdb.d/init.sql:rw
  
  